const types = {
    INITIALISE_STORE: 'INITIALISE_STORE',
    ADD_LANGUAGE: 'ADD_LANGUAGE',
    ADD_TAG: 'ADD_TAG',
    ADD_SNIPPET: 'ADD_SNIPPET',

    SELECT_LANGUAGE: 'SELECT_LANGUAGE',
    SELECT_SNIPPET: 'SELECT_SNIPPET',
    SELECT_TAG: 'SELECT_TAG',

    REMOVE_LANGUAGE: 'REMOVE_LANGUAGE',
    REMOVE_SNIPPET: 'REMOVE_SNIPPET',
    REMOVE_TAG: 'REMOVE_TAG',

    UPDATE_SNIPPET: 'UPDATE_SNIPPET',
    SEARCH_SNIPPET: 'SEARCH_SNIPPET',

    UNDO: 'UNDO',
    UNDO_INCREMENT: 'UNDO_INCREMENT',

    UPDATE_USER_PREFERENCES: 'UPDATE_USER_PREFERENCES'

}

export default types
