const types = {
	ADD_LANGUAGE: 'ADD_LANGUAGE',
	ADD_TAG: 'ADD_TAG',
	ADD_SNIPPET: 'ADD_SNIPPET',

	SELECT_LANGUAGE: 'SELECT_LANGUAGE',
	SELECT_SNIPPET: 'SELECT_SNIPPET',
	SELECT_TAG: 'SELECT_TAG',

	REMOVE_LANGUAGE: 'REMOVE_LANGUAGE',
	REMOVE_SNIPPET: 'REMOVE_SNIPPET',
	REMOVE_TAG: 'REMOVE_TAG',

	EDIT_SNIPPET: 'EDIT_SNIPPET',
	SEARCH_SNIPPET: 'SEARCH_SNIPPET',
}

export default types
